#pragma once

#include "Camera.hpp"
#include "MeshComponent.hpp"
#include "Viewport.hpp"
#include <SDL3/SDL_gpu.h>
#include <SDL3/SDL_keyboard.h>
#include <SDL3/SDL_mouse.h>
#include <asset/AssetManager.hpp>
#include <asset/Scene.hpp>
#include <core/App.hpp>
#include <core/Log.hpp>
#include <core/Utf8.hpp>
#include <core/Window.hpp>
#include <ecs/ComponentRegistry.hpp>
#include <ecs/Manager.hpp>
#include <entry/Entry.hpp>
#include <entt/entity/registry.hpp>
#include <imgui.h>
#include <numbers>
#include <rendering/Bitmap.hpp>
#include <rendering/Buffer.hpp>
#include <rendering/Command.hpp>
#include <rendering/Context.hpp>
#include <rendering/Device.hpp>
#include <rendering/Material.hpp>
#include <rendering/Mesh.hpp>
#include <rendering/Pixel.hpp>
#include <rendering/RenderPass.hpp>
#include <rendering/Texture.hpp>
#include <rendering/VertexTypes.hpp>
#include <rendering/text/BatchRenderer.hpp>
#include <rendering/text/FontAtlas.hpp>
#include <systems/InputEventComponents.hpp>
#include <systems/InputSystem.hpp>
#include <systems/SceneComponents.hpp>
#include <systems/TransformComponent.hpp>